<?php

use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function lightning_media_image_entity_form_display_presave(EntityFormDisplayInterface $display) {
  /** @var EntityFormDisplayInterface $original */
  $original = \Drupal::entityTypeManager()
    ->getStorage($display->getEntityTypeId())
    ->loadUnchanged($display->id());

  // Determine which fields are being added to the display.
  $added = array_diff_key($display->getComponents(), $original->getComponents());

  foreach (array_keys($added) as $field) {
    $id = $display->getTargetEntityTypeId() . '.' . $display->getTargetBundle() . '.' . $field;
    $field = FieldConfig::load($id);

    if ($field->getType() == 'image') {
      $display->setComponent($field->getName(), [
        'type' => 'file_entity_browser',
        'settings' => [
          'entity_browser' => 'image_browser',
          'field_widget_edit' => TRUE,
          'field_widget_remove' => TRUE,
          'view_mode' => 'thumbnail',
          'open' => FALSE,
        ],
      ]);
    }
  }
}
